<?php
function shift_cipher_menu() {
  $items = array();
  $items['shift_cipher'] = array(
    'title' => 'Shift Cipher',
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'page callback' => 'drupal_get_form',
    'page arguments' => array('shift_cipher_form'),
  );

  $items['shift_results'] = array(
    'title' => 'Shift Cipher Results',
    'type' => MENU_CALLBACK,
    'access callback' => TRUE,
    'page callback' => 'shift_cipher_results',
  );
  return $items;
}

//form
function shift_cipher_form() {
  $form = array();
  $form['phrase'] = array(
    '#title' => 'Phrase to shift',
    '#type' => 'textfield',
    '#description' => t('Enter a phrase'),
    '#required' => TRUE,
    '#element_validate' => array('element_validate_string'),
  );

  $form['shift_value'] = array(
    '#title' => 'Value to shift',
    '#type' => 'textfield',
    '#description' => t('Enter the value to shift'),
    '#required' => TRUE,
    '#element_validate' => array('element_validate_integer_positive'),
  );

  $form['shift_direction'] = array(
    '#title' => 'Direction to shift',
    '#type' => 'textfield',
    '#description' => t('Enter left or right'),
    '#required'=> TRUE,
    '#element_validate' => array('element_validate_direction')
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => 'Submit',
  );

  return $form;
}

//form validation
function element_validate_string($element) {
  if (ctype_digit($element['#value'])) {
    form_error($element, t('Must enter a word. No numbers allowed'));
  }
}

function element_validate_direction($element) {
  $direction = strtoupper($element['#value']);
  // $left = 'LEFT';
  // $right = 'RIGHT';
  if ($direction != 'RIGHT' && $direction != 'LEFT') {
    form_error($element, t('Must enter left or right.'));
  }
}

//form submit
function shift_cipher_form_submit($form, &$form_state) {
  $phrase = $form_state['values']['phrase'];
  $shift_value = $form_state['values']['shift_value'];
  $shift_direction = $form_state['values']['shift_direction'];

  $_SESSION['shift_output'] = $phrase;
  $form_state['redirect'] = 'shift_results';
}

//results
function shift_cipher_results() {
  $results = $_SESSION['shift_output'];
  return " $results ";
}
